### ISSUE TITLE
Workflow file doesn't open in Alfred

### ISSUE THREAD

**Issue by astanush** [blainesch/alfred-find-replace#2]
I downloaded the `find-replace.alfredworkflow` file, and double-clicked it to open it in Alfred.

Alfred opens the "Workflows" tab, but the workflow doesn't appear in the list and there's no other indication that it was imported.

Am I missing an installation step? I'm on Alfred 2.8.3.

**Comment by bayleedev** [comment]
I'll take a look!

**Comment by bayleedev** [comment]
I'm also on 2.8.3. After importing I saw the workflow appear, and I went through the workflow and saw the results listed.

Where did you download the workflow? I downloaded it [here](https://github.com/blainesch/alfred-find-replace/raw/master/find-replace.alfredworkflow)

**Comment by astanush** [comment]
The link above works. I think the problem was I manually downloaded the file, because the "Download the alfred workflow to get to work!" link in the README links to:

https://github.com/blainesch/alfred-find-replace/blob/master/find-replace.alfredworkflow

Which does not download the file.

Where the link in your comment above links to:

https://github.com/blainesch/alfred-find-replace/raw/master/find-replace.alfredworkflow

And does initiate the file download.

Thanks!

**Comment by bayleedev** [comment]
@astanush I have removed the workflow from source control and moved it to the releases section of the project. I have also updated the readme to reflect this change.

ea3554106c7a76213d2ef4517ae77416846e022b

I'll close this issue for now, let me know if you find anything else! [:
